[ci] indent script

diff --git a/scripts/opam-coq-install-remove b/scripts/opam-coq-install-remove
--- a/scripts/opam-coq-install-remove
+++ b/scripts/opam-coq-install-remove
@@ -33,63 +33,64 @@ SUCCESSES=
 mkdir -p log
 
 while [ ! -z "$1" ]; do
- if [ -e "$1" ]; then
-  case "$1" in
-  */opam)
-  echo "Failures so far:$FAILURES"
-  echo "Successes so far:$SUCCESSES"
-  LOG=log/`echo $1 | tr '/' '-'`
-  PKG_VERSION_DIR=`dirname "$1"`
-  PKG_NAME_VERSION=`basename "$PKG_VERSION_DIR"`
-  PKG_VERSION=`echo $PKG_NAME_VERSION | cut -d . -f 2-`
-  PKG_NAME=`echo $PKG_NAME_VERSION | cut -d . -f 1`
-  if [ ! -z "${SKIP[$PKG_NAME_VERSION]}" ]; then
-    echo Skip $1
-  else
-    echo Testing $1
-    > $LOG
-    setup_root $LOG
-    case "$PKG_VERSION_DIR" in
-    *core-dev*)
-      echo Add dev repos
-      opam repo add core-dev --all-switches file://$PWD/core-dev >> $LOG
-      opam update core-dev >> $LOG
-    ;;
-    *extra-dev*)
-      echo Add dev repos
-      opam repo add core-dev --all-switches file://$PWD/core-dev >> $LOG
-      opam repo add extra-dev --all-switches file://$PWD/extra-dev >> $LOG
-      opam update core-dev extra-dev >> $LOG
-    ;;
-    *)
-    ;;
+  if [ -e "$1" ]; then
+    case "$1" in
+      */opam)
+        echo "Failures so far:$FAILURES"
+        echo "Successes so far:$SUCCESSES"
+        LOG=log/`echo $1 | tr '/' '-'`
+        PKG_VERSION_DIR=`dirname "$1"`
+        PKG_NAME_VERSION=`basename "$PKG_VERSION_DIR"`
+        PKG_VERSION=`echo $PKG_NAME_VERSION | cut -d . -f 2-`
+        PKG_NAME=`echo $PKG_NAME_VERSION | cut -d . -f 1`
+        if [ ! -z "${SKIP[$PKG_NAME_VERSION]}" ]; then
+          echo Skip $1 due to user request
+        else
+          echo Testing $1
+          > $LOG
+          setup_root $LOG
+          case "$PKG_VERSION_DIR" in
+            *core-dev*)
+              echo Add dev repos
+              opam repo add core-dev --all-switches file://$PWD/core-dev >> $LOG
+              opam update core-dev >> $LOG
+              ;;
+            *extra-dev*)
+              echo Add dev repos
+              opam repo add core-dev --all-switches file://$PWD/core-dev >> $LOG
+              opam repo add extra-dev --all-switches file://$PWD/extra-dev >> $LOG
+              opam update core-dev extra-dev >> $LOG
+              ;;
+            *)
+              echo No repo to add
+              ;;
+          esac
+          echo Check if $PKG_NAME_VERSION is installable
+          if opam install "$PKG_NAME_VERSION" -y --show-action; then
+            set +e
+            echo Installing $PKG_NAME_VERSION
+            opam install "$PKG_NAME_VERSION" -y -v -v >> $LOG
+            if [ $? != 0 ]; then
+              RC=1;
+              FAILURES="$FAILURES $PKG_NAME_VERSION";
+            else
+              SUCCESSES="$SUCCESSES $PKG_NAME_VERSION";
+            fi
+            echo Removing $PKG_NAME
+            opam remove "$PKG_NAME" -y >> $LOG
+            set -e
+          else
+            echo Skipping $PKG_NAME_VERSION since not installable
+          fi
+        fi
+        ;;
+      *)
+        echo Ignoring $1
+        echo
+        ;;
     esac
-    echo Check if $PKG_NAME_VERSION is compatible with the current environment
-    if opam install "$PKG_NAME_VERSION" -y --show-action; then
-      set +e
-      echo Installing $PKG_NAME_VERSION
-      opam install "$PKG_NAME_VERSION" -y -v -v >> $LOG
-      if [ $? != 0 ]; then
-	      RC=1;
-	      FAILURES="$FAILURES $PKG_NAME_VERSION";
-      else
-	      SUCCESSES="$SUCCESSES $PKG_NAME_VERSION";
-      fi
-      echo Removing $PKG_NAME
-      opam remove "$PKG_NAME" -y >> $LOG
-      set -e
-    else
-      echo Skipping $PKG_NAME_VERSION
-    fi
   fi
-  ;;
-  *)
-  echo Ignoring $1
-  echo
-  ;;
-  esac
- fi
- shift
+  shift
 done
 
 echo "Packages that failed to install:$FAILURES"
